#!/usr/bin/env python
# encoding: utf-8
import torch
import torch.nn as nn
from torch import Tensor
from typing import Callable
import torch.nn.functional as F
from torch_geometric.nn.inits import reset
from torch_geometric.typing import Adj, Size
from torch_sparse import SparseTensor, matmul
from torch_geometric.nn import GCNConv, GINConv, SAGEConv
from torch_geometric.nn.conv import MessagePassing


class FeatureEncoder(nn.Module):

    def __init__(self, args):
        super(FeatureEncoder, self).__init__()
        self.args = args
        self.des_size = args.des_num
        self.tweet_size = args.tweet_num
        self.num_prop_size = args.prop_num
        self.cat_prop_size = args.cat_num
        self.dropout = args.dropout
        input_dimension = args.input_dim
        embedding_dimension = args.hidden_dim

        self.linear_relu_des = nn.Sequential(
            nn.Linear(self.des_size, int(input_dimension / 4)), nn.LeakyReLU())
        self.linear_relu_tweet = nn.Sequential(
            nn.Linear(self.tweet_size, int(input_dimension / 4)),
            nn.LeakyReLU())
        self.linear_relu_num_prop = nn.Sequential(
            nn.Linear(self.num_prop_size, int(input_dimension / 4)),
            nn.LeakyReLU())
        self.linear_relu_cat_prop = nn.Sequential(
            nn.Linear(self.cat_prop_size, int(input_dimension / 4)),
            nn.LeakyReLU())

        self.linear_relu_input = nn.Sequential(
            nn.Linear(input_dimension, embedding_dimension),
            nn.PReLU(embedding_dimension))

    def forward(self, x):
        if self.args.dataset == 'twibot-20':
            num_prop = x[:, :self.num_prop_size]
            tweet = x[:,
                      self.num_prop_size:self.num_prop_size + self.tweet_size]
            cat_prop = x[:, self.num_prop_size +
                         self.tweet_size:self.num_prop_size + self.tweet_size +
                         self.cat_prop_size]
            des = x[:,
                    self.num_prop_size + self.tweet_size + self.cat_prop_size:]
            d = self.linear_relu_des(des)
            t = self.linear_relu_tweet(tweet)
            n = self.linear_relu_num_prop(num_prop)
            c = self.linear_relu_cat_prop(cat_prop)
            x = torch.cat((d, t, n, c), dim=1)

        x = self.linear_relu_input(x)
        return x


class SEPooling(MessagePassing):

    def __init__(self, nn: Callable = None, **kwargs):
        kwargs.setdefault('aggr', 'add')
        kwargs.setdefault('flow', 'target_to_source')
        super().__init__(**kwargs)
        self.nn = nn
        self.reset_parameters()

    def reset_parameters(self):
        reset(self.nn)

    def forward(self, x: Tensor, edge_index: Adj, size: Size = None) -> Tensor:
        out = self.propagate(edge_index, x=x, size=size)
        return self.nn(out)

    def message(self, x_j: Tensor) -> Tensor:
        return x_j

    # adj_t is generated by edge_index
    def message_and_aggregate(self, adj_t: SparseTensor, x: Tensor) -> Tensor:
        adj_t = adj_t.set_value(None, layout=None)
        return matmul(
            adj_t, x,
            reduce=self.aggr)  # note that matmul is a function in torch_sparse

    def __repr__(self):
        return '{}(nn={})'.format(self.__class__.__name__, self.nn)


class SEP_U(torch.nn.Module):

    def __init__(self, args):
        super(SEP_U, self).__init__()
        self.args = args
        self.num_features = args.input_dim  # input_dim
        self.nhid = args.hidden_dim  # hidden dim
        self.num_classes = args.num_classes  # output dim
        self.d1 = args.conv_dropout
        self.d2 = args.pooling_dropout
        self.convs = self.get_convs()
        self.sepools = self.get_sepool()
        self.classifier = self.get_classifier()

        self.feature_encoder = FeatureEncoder(args)

    def __process_layer_edgeIndex(self, batch, layer=0):
        if layer == 0:
            return batch['data'].edge_index
        return batch['layer_data']['layer_edgeMat'][layer].to(self.args.device)

    def __process_sep_edgeIndex(self, batch, layer=1):
        return batch['layer_data']['interLayer_edgeMat'][layer].to(
            self.args.device)

    def __process_sep_size(self, batch, layer=1):
        return [
            batch['layer_data']['node_size'][layer],
            batch['layer_data']['node_size'][layer - 1]
        ]

    def get_convs(self):
        convs = nn.ModuleList()
        _input_dim = self.nhid
        _output_dim = self.nhid
        for _ in range(self.args.num_blocks * 2 +
                       1):  # 5 GCN layers, num_blocks = 2
            if _ > self.args.num_blocks:
                _input_dim = 2 * self.nhid
            if _ == self.args.num_blocks * 2:
                if self.args.link_input:
                    _input_dim = 2 * self.nhid + self.nhid
                _output_dim = self.nhid  # # self.num_classes

            if self.args.conv == 'SAGE':
                conv = SAGEConv(_input_dim, _output_dim)
            elif self.args.conv == 'GIN':
                conv = GINConv(nn.Sequential(
                    nn.Linear(_input_dim, _output_dim),
                    nn.ReLU(),
                    nn.Linear(_output_dim, _output_dim),
                    nn.ReLU(),
                    nn.BatchNorm1d(_output_dim),
                ),
                               train_eps=False)
            elif self.args.conv == 'GCN':
                conv = GCNConv(_input_dim, _output_dim)
            convs.append(conv)
            _input_dim = self.nhid
        return convs

    def get_sepool(self):
        pools = nn.ModuleList()
        for _ in range(self.args.num_blocks *
                       2):  # 4 SEPooling layers, num_blocks = 2
            pool = SEPooling(  # adj * x and nn
                nn.Sequential(
                    nn.Linear(self.nhid, self.nhid),
                    nn.ReLU(),
                    nn.BatchNorm1d(self.nhid),
                ))
            pools.append(pool)
        return pools

    def get_classifier(self):
        return nn.Linear(self.nhid, self.nhid)

    def forward(self, batch):
        x = batch['data'].x

        x = xIn = self.feature_encoder(x)
        xs = []
        # down sampling
        for _ in range(self.args.num_blocks):  # layer = 1, 2
            # mp
            edge_index = self.__process_layer_edgeIndex(batch, _)
            x = F.dropout(F.relu(self.convs[_](x, edge_index)),
                          self.d1,
                          training=self.training)
            xs.append(x)
            # sep
            edge_index = self.__process_sep_edgeIndex(batch, _ + 1)
            size = self.__process_sep_size(batch, _ + 1)
            x = F.dropout(F.relu(self.sepools[_](x, edge_index, size=size)),
                          self.d2,
                          training=self.training)

        # up sampling
        for _ in range(self.args.num_blocks, 0, -1):
            # mp
            edge_index = self.__process_layer_edgeIndex(batch, _)
            x = F.dropout(F.relu(self.convs[self.args.num_blocks * 2 - _](
                x, edge_index)),
                          self.d1,
                          training=self.training)
            # sep_u
            edge_index = self.__process_sep_edgeIndex(batch, _)
            size = self.__process_sep_size(batch, _)
            size.reverse()
            x = F.dropout(F.relu(self.sepools[self.args.num_blocks * 2 - _](
                x, edge_index[[1, 0]], size=size)),
                          self.d2,
                          training=self.training)
            x = torch.cat([x, xs[_ - 1]], dim=1)

        # last conv
        edge_index = self.__process_layer_edgeIndex(batch, 0)
        # link input
        if self.args.link_input:
            x = torch.cat([x, xIn], dim=1)
        x = self.convs[-1](x, edge_index)

        # For Classification
        x = self.classifier(x)
        return x
